### ISSUE TITLE
NOT NULL Constraints configuration

### ISSUE THREAD

**Issue by Zoxive** [mm716783/naorm-sqlite#87]
First off awesome library! I think I want to use this for a new project im starting on. I too want full control over the SQL, and have no problem writing my SQL files myself. I dont want to depend on an ORM's specific implementation for how they build their queries.

**Is your feature request related to a problem? Please describe.**
I think there should be a configuration setting for opting into reading NOT NULL constraints instead of an additional ` /* NAORM-TYPE: INT NOT NULL */` comment added to all my create table statements.

**Describe the solution you'd like**
Maybe we can add a setting in `NAORMConfig.json`

**Describe alternatives you've considered**
 Adding the comment to all my columns for now.. but it feels odd that right next to it i already have NOT NULL.

**Comment by mm716783** [comment]
Hi @Zoxive, thanks for the positive feedback and the suggestion. I think this makes sense as a configuration option. I looked into it and created a draft PR. I'll put a bit more thought into it before updating the docs and going forward with the merge / release.

**Comment by jlarmstrongiv** [comment]
I use `NOT NULL` in the majority of my SQLite database, and it’d be wonderful to remove null from the types for `CREATE TABLE` and `?` placeholders 😄

**Comment by mm716783** [comment]
Hi @Zoxive  and @jlarmstrongiv, I've gone ahead and updated the docs and have released a new version with the updates to the NOT NULL configuration.

Please see the note on the PR about the breaking changes:
https://github.com/mm716783/naorm-sqlite/pull/88#issuecomment-1837242811

Thanks again for the feedback and for using NAORM.
